# Generated by Django 4.0.5 on 2022-06-07 14:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('login', models.CharField(max_length=4)),
                ('password', models.CharField(max_length=8)),
                ('sex', models.CharField(max_length=5)),
            ],
        ),
    ]
